# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.products_api import ProductsApi  # noqa: E501


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_plan_subscription(self) -> None:
        """Test case for create_plan_subscription

        Create Plan Subscription  # noqa: E501
        """
        pass

    def test_get_product(self) -> None:
        """Test case for get_product

        Get Product  # noqa: E501
        """
        pass

    def test_get_product_lever(self) -> None:
        """Test case for get_product_lever

        Get Product Lever  # noqa: E501
        """
        pass

    def test_get_product_plan(self) -> None:
        """Test case for get_product_plan

        Get Product Plan  # noqa: E501
        """
        pass

    def test_get_product_plan_entitlements(self) -> None:
        """Test case for get_product_plan_entitlements

        Get Product Plan Entitlements  # noqa: E501
        """
        pass

    def test_list_product_levers(self) -> None:
        """Test case for list_product_levers

        List Product Levers  # noqa: E501
        """
        pass

    def test_list_product_plans(self) -> None:
        """Test case for list_product_plans

        List Product Plans  # noqa: E501
        """
        pass

    def test_list_products(self) -> None:
        """Test case for list_products

        List Products  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
