# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.customer_in_db_base import CustomerInDbBase  # noqa: E501

class TestCustomerInDbBase(unittest.TestCase):
    """CustomerInDbBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerInDbBase:
        """Test CustomerInDbBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerInDbBase`
        """
        model = CustomerInDbBase()  # noqa: E501
        if include_optional:
            return CustomerInDbBase(
                id = '',
                metadata_ = planship_openapi_gen.models.metadata_.Metadata (),
                name = '',
                email = '',
                alternative_id = '',
                organization_id = ''
            )
        else:
            return CustomerInDbBase(
                id = '',
                organization_id = '',
        )
        """

    def testCustomerInDbBase(self):
        """Test CustomerInDbBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
