# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.plan_entitlement import PlanEntitlement  # noqa: E501

class TestPlanEntitlement(unittest.TestCase):
    """PlanEntitlement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanEntitlement:
        """Test PlanEntitlement
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanEntitlement`
        """
        model = PlanEntitlement()  # noqa: E501
        if include_optional:
            return PlanEntitlement(
                value = '',
                name = '',
                description = '',
                order = 56,
                configuration = planship_openapi_gen.models.configuration.Configuration()
            )
        else:
            return PlanEntitlement(
                value = '',
                name = '',
                description = '',
        )
        """

    def testPlanEntitlement(self):
        """Test PlanEntitlement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
