# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.customer_subscriptions_api import CustomerSubscriptionsApi  # noqa: E501


class TestCustomerSubscriptionsApi(unittest.TestCase):
    """CustomerSubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomerSubscriptionsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_plan_subscription_for_customer(self) -> None:
        """Test case for create_plan_subscription_for_customer

        Create Plan Subscription For Customer  # noqa: E501
        """
        pass

    def test_get_customer_plan_subscription(self) -> None:
        """Test case for get_customer_plan_subscription

        Get Customer Plan Subscription  # noqa: E501
        """
        pass

    def test_list_customer_plan_subscriptions(self) -> None:
        """Test case for list_customer_plan_subscriptions

        List Customer Plan Subscriptions  # noqa: E501
        """
        pass

    def test_modify_customer_plan_subscription(self) -> None:
        """Test case for modify_customer_plan_subscription

        Modify Customer Plan Subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
