# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.subscription_customer_add import SubscriptionCustomerAdd  # noqa: E501

class TestSubscriptionCustomerAdd(unittest.TestCase):
    """SubscriptionCustomerAdd unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionCustomerAdd:
        """Test SubscriptionCustomerAdd
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionCustomerAdd`
        """
        model = SubscriptionCustomerAdd()  # noqa: E501
        if include_optional:
            return SubscriptionCustomerAdd(
                metadata = planship_openapi_gen.models.metadata.Metadata(),
                is_administrator = True,
                is_subscriber = True,
                customer_id = ''
            )
        else:
            return SubscriptionCustomerAdd(
                customer_id = '',
        )
        """

    def testSubscriptionCustomerAdd(self):
        """Test SubscriptionCustomerAdd"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
