# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.id_name_slug_orm_base import IdNameSlugOrmBase  # noqa: E501

class TestIdNameSlugOrmBase(unittest.TestCase):
    """IdNameSlugOrmBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IdNameSlugOrmBase:
        """Test IdNameSlugOrmBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IdNameSlugOrmBase`
        """
        model = IdNameSlugOrmBase()  # noqa: E501
        if include_optional:
            return IdNameSlugOrmBase(
                id = '',
                name = '',
                slug = ''
            )
        else:
            return IdNameSlugOrmBase(
                id = '',
                name = '',
                slug = '',
        )
        """

    def testIdNameSlugOrmBase(self):
        """Test IdNameSlugOrmBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
