# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.customers_api import CustomersApi  # noqa: E501


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomersApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_customer(self) -> None:
        """Test case for create_customer

        Create Customer  # noqa: E501
        """
        pass

    def test_delete_customer(self) -> None:
        """Test case for delete_customer

        Delete Customer  # noqa: E501
        """
        pass

    def test_get_customer(self) -> None:
        """Test case for get_customer

        Get Customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
