# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.public_api import PublicApi  # noqa: E501


class TestPublicApi(unittest.TestCase):
    """PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_public_plan(self) -> None:
        """Test case for get_public_plan

        Get Public Plan  # noqa: E501
        """
        pass

    def test_list_public_plans(self) -> None:
        """Test case for list_public_plans

        List Public Plans  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
