# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.subscription_customer_in_db_base import SubscriptionCustomerInDbBase  # noqa: E501

class TestSubscriptionCustomerInDbBase(unittest.TestCase):
    """SubscriptionCustomerInDbBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionCustomerInDbBase:
        """Test SubscriptionCustomerInDbBase
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionCustomerInDbBase`
        """
        model = SubscriptionCustomerInDbBase()  # noqa: E501
        if include_optional:
            return SubscriptionCustomerInDbBase(
                metadata_ = planship_openapi_gen.models.metadata_.Metadata (),
                is_administrator = True,
                is_subscriber = True,
                customer_id = '',
                subscription_id = ''
            )
        else:
            return SubscriptionCustomerInDbBase(
                customer_id = '',
                subscription_id = '',
        )
        """

    def testSubscriptionCustomerInDbBase(self):
        """Test SubscriptionCustomerInDbBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
