# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.entitlements_api import EntitlementsApi  # noqa: E501


class TestEntitlementsApi(unittest.TestCase):
    """EntitlementsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EntitlementsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_product_entitlements_for_customer(self) -> None:
        """Test case for get_product_entitlements_for_customer

        Get Product Entitlements For Customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
