# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.time_units import TimeUnits  # noqa: E501

class TestTimeUnits(unittest.TestCase):
    """TimeUnits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeUnits(self):
        """Test TimeUnits"""
        # inst = TimeUnits()

if __name__ == '__main__':
    unittest.main()
