# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.plan_subscription_create import PlanSubscriptionCreate  # noqa: E501

class TestPlanSubscriptionCreate(unittest.TestCase):
    """PlanSubscriptionCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanSubscriptionCreate:
        """Test PlanSubscriptionCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanSubscriptionCreate`
        """
        model = PlanSubscriptionCreate()  # noqa: E501
        if include_optional:
            return PlanSubscriptionCreate(
                metadata = planship_openapi_gen.models.metadata.Metadata(),
                customer_id = '',
                is_subscriber = True,
                max_subscribers = 56,
                renew_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                auto_renew = True
            )
        else:
            return PlanSubscriptionCreate(
                customer_id = '',
        )
        """

    def testPlanSubscriptionCreate(self):
        """Test PlanSubscriptionCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
