# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.subscription_customers_api import SubscriptionCustomersApi  # noqa: E501


class TestSubscriptionCustomersApi(unittest.TestCase):
    """SubscriptionCustomersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionCustomersApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_add_customer_to_subscription(self) -> None:
        """Test case for add_customer_to_subscription

        Add Customer To Subscription  # noqa: E501
        """
        pass

    def test_list_subscription_customers(self) -> None:
        """Test case for list_subscription_customers

        List Subscription Customers  # noqa: E501
        """
        pass

    def test_remove_customer_from_subscription(self) -> None:
        """Test case for remove_customer_from_subscription

        Remove Customer From Subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
