# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.metering_record import MeteringRecord  # noqa: E501

class TestMeteringRecord(unittest.TestCase):
    """MeteringRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MeteringRecord:
        """Test MeteringRecord
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MeteringRecord`
        """
        model = MeteringRecord()  # noqa: E501
        if include_optional:
            return MeteringRecord(
                id = '',
                is_allocated = True,
                usage = 56,
                metering_id = '',
                customer_id = '',
                product_id = '',
                subscription_id = '',
                bucket = ''
            )
        else:
            return MeteringRecord(
                id = '',
                usage = 56,
                metering_id = '',
                customer_id = '',
                product_id = '',
        )
        """

    def testMeteringRecord(self):
        """Test MeteringRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
