# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.organization_customer_create import OrganizationCustomerCreate  # noqa: E501

class TestOrganizationCustomerCreate(unittest.TestCase):
    """OrganizationCustomerCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationCustomerCreate:
        """Test OrganizationCustomerCreate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationCustomerCreate`
        """
        model = OrganizationCustomerCreate()  # noqa: E501
        if include_optional:
            return OrganizationCustomerCreate(
                metadata = planship_openapi_gen.models.metadata.Metadata(),
                name = '',
                email = '',
                alternative_id = ''
            )
        else:
            return OrganizationCustomerCreate(
        )
        """

    def testOrganizationCustomerCreate(self):
        """Test OrganizationCustomerCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
