# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.metered_usage_api import MeteredUsageApi  # noqa: E501


class TestMeteredUsageApi(unittest.TestCase):
    """MeteredUsageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MeteredUsageApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_lever_usage_for_customer(self) -> None:
        """Test case for get_lever_usage_for_customer

        Get Lever Usage For Customer  # noqa: E501
        """
        pass

    def test_get_metering_id_levers_usage_for_customer(self) -> None:
        """Test case for get_metering_id_levers_usage_for_customer

        Get Metering Id Levers Usage For Customer  # noqa: E501
        """
        pass

    def test_report_metered_usage_for_customer(self) -> None:
        """Test case for report_metered_usage_for_customer

        Report Metered Usage For Customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
