# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.subscriptions_api import SubscriptionsApi  # noqa: E501


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_force_renew_subscription(self) -> None:
        """Test case for force_renew_subscription

        Force Renew Subscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
