# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from planship_openapi_gen.models.lever_usage import LeverUsage  # noqa: E501

class TestLeverUsage(unittest.TestCase):
    """LeverUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LeverUsage:
        """Test LeverUsage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LeverUsage`
        """
        model = LeverUsage()  # noqa: E501
        if include_optional:
            return LeverUsage(
                total = 56,
                by_bucket = {
                    'key' : 56
                    },
                by_subscription = {
                    'key' : [
                        planship_openapi_gen.models.bucket_usage.BucketUsage(
                            usage = 56, 
                            bucket = '', )
                        ]
                    }
            )
        else:
            return LeverUsage(
                total = 56,
                by_bucket = {
                    'key' : 56
                    },
                by_subscription = {
                    'key' : [
                        planship_openapi_gen.models.bucket_usage.BucketUsage(
                            usage = 56, 
                            bucket = '', )
                        ]
                    },
        )
        """

    def testLeverUsage(self):
        """Test LeverUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
