# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from planship_openapi_gen.api.auth_api import AuthApi  # noqa: E501


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_access_token(self) -> None:
        """Test case for get_access_token

        Get Access Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
