# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class PlanEntitlement(BaseModel):
    """
    PlanEntitlement
    """
    value: StrictStr = Field(..., description="Formatted text representation of the entitlement value")
    name: StrictStr = Field(..., description="Entitlement name")
    description: StrictStr = Field(..., description="Entitlement description")
    order: Optional[StrictInt] = Field(None, description="Entitlement display order")
    configuration: Optional[Dict[str, Any]] = Field(None, description="Entitlement configuration object")
    __properties = ["value", "name", "description", "order", "configuration"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PlanEntitlement:
        """Create an instance of PlanEntitlement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PlanEntitlement:
        """Create an instance of PlanEntitlement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PlanEntitlement.parse_obj(obj)

        _obj = PlanEntitlement.parse_obj({
            "value": obj.get("value"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "order": obj.get("order"),
            "configuration": obj.get("configuration")
        })
        return _obj


