# coding: utf-8

"""
    Planship API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from planship_openapi_gen.models.id_name_slug_orm_base import IdNameSlugOrmBase

class SubscriptionWithPlan(BaseModel):
    """
    SubscriptionWithPlan
    """
    id: StrictStr = Field(...)
    auto_renew: StrictBool = Field(...)
    is_active: StrictBool = Field(...)
    plan_id: StrictStr = Field(...)
    renew_plan_id: StrictStr = Field(...)
    renew_at: datetime = Field(...)
    last_renewed_at: datetime = Field(...)
    max_subscribers: StrictInt = Field(...)
    start_at: datetime = Field(...)
    plan: IdNameSlugOrmBase = Field(...)
    renew_plan: IdNameSlugOrmBase = Field(...)
    __properties = ["id", "auto_renew", "is_active", "plan_id", "renew_plan_id", "renew_at", "last_renewed_at", "max_subscribers", "start_at", "plan", "renew_plan"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SubscriptionWithPlan:
        """Create an instance of SubscriptionWithPlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of plan
        if self.plan:
            _dict['plan'] = self.plan.to_dict()
        # override the default output from pydantic by calling `to_dict()` of renew_plan
        if self.renew_plan:
            _dict['renew_plan'] = self.renew_plan.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SubscriptionWithPlan:
        """Create an instance of SubscriptionWithPlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SubscriptionWithPlan.parse_obj(obj)

        _obj = SubscriptionWithPlan.parse_obj({
            "id": obj.get("id"),
            "auto_renew": obj.get("auto_renew"),
            "is_active": obj.get("is_active"),
            "plan_id": obj.get("plan_id"),
            "renew_plan_id": obj.get("renew_plan_id"),
            "renew_at": obj.get("renew_at"),
            "last_renewed_at": obj.get("last_renewed_at"),
            "max_subscribers": obj.get("max_subscribers"),
            "start_at": obj.get("start_at"),
            "plan": IdNameSlugOrmBase.from_dict(obj.get("plan")) if obj.get("plan") is not None else None,
            "renew_plan": IdNameSlugOrmBase.from_dict(obj.get("renew_plan")) if obj.get("renew_plan") is not None else None
        })
        return _obj


